inherit_from: .rubocop_todo.yml

  
Metrics/AbcSize: 
  Enabled: false
Metrics/MethodLength: 
  Enabled: false
Style/ClassAndModuleChildren:
  Enabled: false
Style/Documentation: 
  Enabled: false
Style/StringLiterals: 
  Enabled: false